# Generated by Django 4.2.5 on 2023-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_original",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("image_small", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "image_medium",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "image_custom",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
