# Generated by Django 4.2.5 on 2023-09-27 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpirationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("available_to", models.PositiveIntegerField()),
                ("image", models.CharField(max_length=255)),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
